name: CI

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: composer validate --strict

      - id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles("**/composer.lock") }}
          restore-keys: ${{ runner.os }}-composer-

      - run: composer install --prefer-dist --no-progress

      - run: composer run-script test || true # ignore exit code, we're only interested in the TAP results
